import { transformUrl } from '@/utils/url';

export const menuConfig = [
  /*{
    id: '900040',
    url: '',
    deep: 0,
    title: '目录',
    anchor: '#目录',
    count: 0,
    path: '/900040',
    jumpType: 1,
    css: '',
    children: [
      {
        id: '900041',
        url: '',
        baseUrl: '',
        deep: 1,
        title: '常用',
        anchor: '#常用',
        count: 0,
        path: '900040/900041',
        jumpType: 1,
        css: '',
        children: [
          {
            id: '900042',
            url: '/detail/enterprise/overview',
            baseUrl: '',
            deep: 2,
            title: '企业图谱',
            anchor: '#企业图谱',
            count: 0,
            path: '900040/900041/900042',
            jumpType: 1,
            css: '',
          },
          {
            id: '900043',
            url: '/detail/enterprise/corporateFinancing',
            baseUrl: '',
            deep: 2,
            title: '融资图谱',
            anchor: '#融资图谱',
            count: 23,
            path: '900040/900041/900043',
            jumpType: 1,
            css: '',
          },
          {
            id: '900044',
            url: '/detail/enterprise/financial',
            baseUrl: '',
            deep: 2,
            title: '财务主要指标',
            anchor: '#主要指标',
            count: 0,
            path: '900040/900041/900044',
            jumpType: 1,
            css: '',
          },
          {
            id: '900045',
            url: '/detail/enterprise/credit',
            baseUrl: '',
            deep: 2,
            title: '诚信档案',
            anchor: '#诚信档案',
            count: 33,
            path: '900040/900041/900045',
            jumpType: 1,
            css: '',
          },
          {
            id: '900046',
            url: '/detail/enterprise/judicial',
            baseUrl: '',
            deep: 2,
            title: '裁判文书',
            anchor: '#裁判文书',
            count: 1287,
            path: '900040/900041/900046',
            jumpType: 1,
            css: '',
          },
        ],
      },
    ],
  },*/
  {
    id: '1001',
    url: '/area/regionEconomy',
    baseUrl: '/area/regionEconomy',
    deep: 0,
    title: '地区经济',
    // anchor: '#本地区经济',
    count: 10,
    path: '/1001',
    jumpType: 1,
    child_type: 'companyInfo',
    icon: transformUrl('https://cdn.finchina.com/app/pic/f9/icon/companyInfo.png'),
    css: '',
  },
  // {
  //   id: '1001',
  //   url: '/area/regionEconomy',
  //   deep: 0,
  //   title: '区域经济',
  //   // anchor: '#地区经济',
  //   count: 0,
  //   path: '/1001',
  //   jumpType: 1,
  //   icon: '#iconicon_qyf9ml_qygy1',
  //   css: '',
  //   children: [
  //     /* ,*/
  //   ],
  // },
  {
    id: '1003',
    url: '',
    baseUrl: '/area/underArea',
    deep: 1,
    title: '下属辖区',
    anchor: '#下属辖区',
    count: 0,
    path: '1001/1003',
    jumpType: 1,
    child_type: 'seniorExecutive',
    icon: transformUrl('https://cdn.finchina.com/app/pic/f9/icon/seniorExecutive.png'),
    css: '',
  },
  {
    id: '1004',
    url: '',
    baseUrl: '/area/similarEconomy',
    deep: 1,
    title: '相似经济',
    anchor: '#相似经济',
    count: 0,
    path: '1001/1003',
    jumpType: 1,
    child_type: 'seniorExecutive',
    icon: transformUrl('https://cdn.finchina.com/app/pic/f9/icon/seniorExecutive.png'),
    css: '',
  },
  {
    id: '2002',
    url: '',
    baseUrl: '/area/platforms',
    deep: 1,
    title: '城投平台',
    anchor: '#城投平台',
    count: 0,
    path: '4501/4502',
    jumpType: 1,
    child_type: 'financeGraph',
    icon: transformUrl('https://cdn.finchina.com/app/pic/f9/icon/financeGraph.png'),
    css: '',
  },
  {
    id: '2003',
    url: '',
    baseUrl: '/area/areaSpreads',
    deep: 1,
    title: '地区利差',
    anchor: '#地区利差',
    count: 0,
    path: '4501/4505',
    jumpType: 1,
    child_type: 'bondFinancing',
    icon: transformUrl('https://cdn.finchina.com/app/pic/f9/icon/bondFinancing.png'),
    css: '',
  },
  // {
  //   id: '2001',
  //   url: '/area/areaEconomy/financingPlatforms',
  //   deep: 0,
  //   title: '融资平台',
  //   anchor: '#融资平台',
  //   count: 0,
  //   path: '/4501',
  //   jumpType: 1,
  //   icon: '#iconicon_qyf9ml_qyrz1',
  //   css: '',
  //   children: [

  //   ],
  // },
  {
    id: '3002',
    url: '',
    baseUrl: '/area/localDebtIssue',
    deep: 1,
    title: '地方债发行',
    anchor: '#地方债发行',
    count: 0,
    path: '3001/3002',
    jumpType: 1,
    child_type: 'mainIndicatorsF9',
    icon: '#iconicon_qyf9ml_cwsj',
    css: '',
  },
  {
    id: '3003',
    url: '',
    baseUrl: '/area/specialDebtProjects',
    deep: 1,
    title: '专项债项目',
    anchor: '#专项债项目',
    count: 0,
    path: '3001/3003',
    jumpType: 1,
    icon: '#iconicon_cwsj_zxsj',
    css: '',
  },
  // {
  //   id: '3001',
  //   url: '/area/areaEconomy/localDept',
  //   deep: 0,
  //   title: '地方债及项目',
  //   anchor: '#地方债及项目',
  //   count: 0,
  //   path: '/3001',
  //   jumpType: 1,
  //   icon: '#iconicon_zq_dqjj',
  //   css: '',
  //   children: [

  //     {
  //       id: '3004',
  //       url: '',
  //       baseUrl: '/area/areaEconomy/localDept',
  //       deep: 1,
  //       title: '项目明细',
  //       anchor: '#项目明细',
  //       count: 0,
  //       path: '3001/3004',
  //       jumpType: 1,
  //       icon: '#iconicon_cwsj_zxsj',
  //       css: '',
  //     },
  //   ],
  // },
];
