import {
  LINK_FINACING_INSTITUTION_BANK,
  LINK_FINACING_INSTITUTION_BOND,
  LINK_FINACING_INSTITUTION_FUND,
  LINK_FINACING_INSTITUTION_INSURANCE,
  LINK_FINACING_INSTITUTION_RENT,
  LINK_FINACING_INSTITUTION_TRUST,
} from '@/configs/routerMap';

import { TabsMap } from './tabsConfig';

const config: { [key: string]: string } = {
  [TabsMap.YH]: LINK_FINACING_INSTITUTION_BANK,
  [TabsMap.ZQ]: LINK_FINACING_INSTITUTION_BOND,
  [TabsMap.BX]: LINK_FINACING_INSTITUTION_INSURANCE,
  [TabsMap.XT]: LINK_FINACING_INSTITUTION_TRUST,
  [TabsMap.ZL]: LINK_FINACING_INSTITUTION_RENT,
  [TabsMap.JJ]: LINK_FINACING_INSTITUTION_FUND,
};

export default config;
